spring.application.name=heic-to-pdf
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.port=8081
server.error.include-message=always
springdoc.api-docs.path=/api/docs
springdoc.swagger-ui.path=/swagger-ui.html
